version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.9.1
    command:
      - "run"
      - "--server"
      - "--log-level=debug"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
      - 8181:8181
    restart: always

  filesys:
    image: python:2.7
    volumes:
      - ./policies:/usr/src
    command: bash -c "cd /usr/src && python -m SimpleHTTPServer"
